name: deploy-prod-ocir

on:
  push:
    tags:
      - prod/*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04-arm
    env:
      IMAGE_TAG: ${{ github.run_number }}
      BUILD_NUMBER: ${{ github.run_number }}
      OCIR_REGISTRY: yny.ocir.io
      OCIR_NAMESPACE: ax1dvc8vmenm
      OCIR_REPOSITORY: snutt-prod/snutt-ev-web

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to OCIR
        run: echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login $OCIR_REGISTRY -u $OCIR_NAMESPACE/members/waffle-deployer --password-stdin

      - name: Docker Build, tag, and push image to OCIR
        id: build-image
        run: |
          docker build -t $OCIR_REGISTRY/$OCIR_NAMESPACE/$OCIR_REPOSITORY:$IMAGE_TAG \
            --build-arg APP_ENV=prod \
            --build-arg GIT_SHA=$(git rev-parse HEAD) \
            --build-arg GIT_TAG=$(git describe --tags) \
            --build-arg TRUFFLE_APIKEY=${{ secrets.TRUFFLE_APIKEY }} \
            .
          docker push $OCIR_REGISTRY/$OCIR_NAMESPACE/$OCIR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$OCIR_REGISTRY/$OCIR_NAMESPACE/$OCIR_REPOSITORY:$IMAGE_TAG"
